version: '3.1'

services:
  html-template:
    build: .
    restart: always
    depends_on:
      - postgres
    environment:
      - SECRET=${SECRET}
      - DB_SOURCE=${DB_SOURCE}
    volumes:
      - ./resources:/app/resources
  caddy:
    image: "caddy:latest"
    ports:
      - 80:80
      - 443:443
    depends_on: 
      - html-template
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    restart: always
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
